# Generated by Django 6.0.1 on 2026-02-07 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_type', models.CharField(choices=[('channel', 'Channel'), ('video', 'Video')], max_length=10)),
                ('youtube_id', models.CharField(help_text='ID of channel or video in Youtube', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Youtube Analysis',
                'verbose_name_plural': 'Youtube Analyses',
            },
        ),
        migrations.CreateModel(
            name='AnalysisQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='analysis.youtubeanalysis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='youtubeanalysis',
            index=models.Index(fields=['user', 'youtube_id'], name='analysis_yo_user_id_9c572f_idx'),
        ),
    ]
