# Generated by Django 6.0.1 on 2026-04-25 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysissuggestion",
            options={"ordering": ["category"]},
        ),
        migrations.AlterModelOptions(
            name="analysistopic",
            options={"ordering": ["-relevance_score"]},
        ),
        migrations.RenameIndex(
            model_name="analysis",
            new_name="analysis_an_user_id_3506de_idx",
            old_name="analysis_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="analysis",
            new_name="analysis_an_user_id_8f0fa9_idx",
            old_name="analysis_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="channel",
            new_name="analysis_ch_youtube_dfd335_idx",
            old_name="channel_yt_id_idx",
        ),
        migrations.RenameIndex(
            model_name="video",
            new_name="analysis_vi_youtube_90e3ba_idx",
            old_name="video_yt_id_idx",
        ),
        migrations.AlterField(
            model_name="analysis",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="analysisquestion",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content", "Content"),
                    ("engagement", "Engagement"),
                    ("growth", "Growth"),
                    ("monetization", "Monetization"),
                    ("audience", "Audience"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="analysisquestion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="analysissuggestion",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content", "Content"),
                    ("engagement", "Engagement"),
                    ("growth", "Growth"),
                    ("monetization", "Monetization"),
                    ("audience", "Audience"),
                    ("custom", "Custom"),
                ],
                default="content",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="analysissuggestion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="analysistopic",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="analysisvideo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
